class PlayerStatus():
    REGIST_NAME = 1
    WAIT_PLAYER = 2
    GAME_PREPARE = 3
    GAME_LOOK_FIRST_HAND = 4
    GAME_BEGINNING_OF_TURN = 5
    GAME_MY_TURN = 6
    GAME_OTHER_PLAYER_TURN = 7
    GAME_END_OF_TURN = 8
    GAME_START_CHANGE_CARD = 9
    GAME_SELECT_CHANGE_CARD = 10
    GAME_JUDGE_HAND = 11
