class PlayerStatus():
    WAIT_PLAYER = 1
    GAME_PREPARE = 2
    GAME_LOOK_FIRST_HAND = 3
    GAME_BEGINNING_OF_TURN = 4
    GAME_MY_TURN = 5
    GAME_OTHER_PLAYER_TURN = 6
    GAME_END_OF_TURN = 7
    GAME_START_CHANGE_CARD = 8
    GAME_SELECT_CHANGE_CARD = 9
    GAME_JUDGE_HAND = 10
